services:

  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www

  app:
    build: ./docker/php
    volumes:
      - ./:/var/www/